-- DATOS INICIALES en la tabla PERSONA.
select * from fx_ins_persons('[{"code":"PER-0001","father_last_name":"Gomez","mother_last_name":"Perez","names":"Juan Carlos","gender":"M","created_by":null},{"code":"PER-0002","father_last_name":"Lopez","mother_last_name":"Ramirez","names":"Maria Fernanda","gender":"F","created_by":1},{"code":"PER-0003","father_last_name":"Sanchez","mother_last_name":"Torres","names":"Luis Alberto","gender":"M","created_by":1},{"code":"PER-0004","father_last_name":"Vega","mother_last_name":"Salazar","names":"Ana Cecilia","gender":"F","created_by":2}]');

-- DATOS INICIALES DE LAS DEMAS TABLAS.
SELECT * FROM fx_ins_types('[{"code":"M","type":"GENERO","name":"Masculino","description":"Genero Masculino","status":true,"created_by":1}, {"code":"F","type":"GENERO","name":"Femenino","description":"Genero Femenino","status":true,"created_by":1}]');
SELECT * FROM fx_ins_types('[{"code":"A","type":"ESTADO-DE-REGISTRO","name":"Activo","description":"Estado Activo","status":true}, {"code":"I","type":"ESTADO-DE-REGISTRO","name":"Inactivo","description":"Estado Inactivo","status":true}]');

SELECT * FROM fx_ins_periods('[{"code":"BIM","name":"BIMESTRE","duration_in_months":2,"status":true,"created_by":1}, {"code":"TRI","name":"TRIMESTRE","duration_in_months":3,"status":true,"created_by":1}]');
SELECT * FROM fx_ins_courses('[{"code":"MAT101","name":"Matemáticas Básicas","description":"Curso introductorio de matemáticas","status":true,"created_by":1}, {"code":"LIT201","name":"Literatura Clásica","description":"Análisis de obras clásicas","status":true,"created_by":1}, {"code":"HIS301","name":"Historia Universal","description":"Historia desde la antigüedad hasta la era moderna","status":true,"created_by":1}]');
SELECT * FROM fx_ins_students('[{"person_id":1,"status":1,"created_by":1}, {"person_id":2,"status":1,"created_by":1}, {"person_id":3,"status":1,"created_by":1}]');
SELECT * FROM fx_ins_attendances('[{"student_id":1,"created_at":"2025-08-14T08:00:00","obs":"Puntual","status":1,"created_by":1}, {"student_id":2,"created_at":"2025-08-14T08:05:00","obs":"Tarde","status":2,"created_by":1}, {"student_id":3,"created_at":"2025-08-14T00:00:00","obs":"Falta","status":3,"created_by":1}]');
SELECT * FROM fx_ins_descriptive_conclusions('[{"student_id":1,"period_id":1,"score":18.50,"achievement":"Excelente desempeño","difficulty":"Ninguna","recommedation":"Seguir igual","obs":"Participativo","status":true,"created_by":1}, {"student_id":2,"period_id":1,"score":14.00,"achievement":"Cumple lo esperado","difficulty":"Matemáticas","recommedation":"Refuerzo en cálculos","obs":"Buen comportamiento","status":true,"created_by":1}]');
SELECT * FROM fx_ins_scores('[{"student_id":1,"period_id":1,"score":19.00,"achievement":"Destacado","difficulty":"Ninguna","recommedation":"Seguir reforzando","obs":"Excelente asistencia","status":true,"created_by":1}, {"student_id":2,"period_id":1,"score":12.50,"achievement":"Regular","difficulty":"Física","recommedation":"Clases de apoyo","obs":"Debe participar más","status":true,"created_by":1}]');
